companySymbol = [
  "AAPL",
  "MSFT",
  "GOOGL",
  "AMZN",
  "META",
  "NVDA",
  "TSLA",
  "HPQ",
  "JNJ",
  "V",
  "WMT",
  "JPM",
  "PG",
  "MA",
  "UNH",
  "DIS",
  "HD",
  "BAC",
  "XOM",
  "CVX",
  "KO",
  "PEP",
  "COST",
  "PFE",
  "MRK",
  "TMO",
  "MCD",
  "CRM",
  "CSCO",
  "ABT",
  "ACN",
  "NFLX",
  "ADBE",
  "INTC",
  "AMD",
  "CMCSA",
  "NKE",
  "TXN",
  "PM",
  "LIN",
  "NEE",
  "UNP",
  "ORCL",
  "WFC",
  "QCOM",
  "HON",
  "UPS",
  "RTX",
  "BA",
  "IBM",
  "LLY",
  "SBUX",
  "GE",
  "CAT",
  "GS",
  "MS",
  "BLK",
  "MMM",
  "C",
  "AXP",
  "T",
  "VZ",
  "F",
  "GM",
  "TGT",
  "LOW",
  "CVS",
  "WBA",
  "BMY",
  "GILD",
  "AMGN",
  "ISRG",
  "MDT",
  "SYK",
  "SPGI",
  "INTU",
  "NOW",
  "PYPL",
  "SQ",
  "UBER",
  "ABNB",
  "SNOW",
  "PLTR",
  "ROKU",
  "ZM",
  "DOCU",
  "SPOT",
  "SHOP",
  "CRWD",
  "NET",
  "DDOG",
  "TEAM",
  "OKTA",
  "ZS",
  "PANW",
  "FTNT",
  "LMT",
  "NOC",
  "GD",
  "DE",
  "WM",
];

companySymbolAndName = [
  { sembol: "AAPL", isim: "Apple Inc." },
  { sembol: "MSFT", isim: "Microsoft Corporation" },
  { sembol: "GOOGL", isim: "Alphabet Inc." },
  { sembol: "AMZN", isim: "Amazon.com Inc." },
  { sembol: "META", isim: "Meta Platforms Inc." },
  { sembol: "NVDA", isim: "NVIDIA Corporation" },
  { sembol: "TSLA", isim: "Tesla Inc." },
  { sembol: "HPQ", isim: "HP Inc." },
  { sembol: "JNJ", isim: "Johnson & Johnson" },
  { sembol: "V", isim: "Visa Inc." },
  { sembol: "WMT", isim: "Walmart Inc." },
  { sembol: "JPM", isim: "JPMorgan Chase & Co." },
  { sembol: "PG", isim: "The Procter & Gamble Company" },
  { sembol: "MA", isim: "Mastercard Incorporated" },
  { sembol: "UNH", isim: "UnitedHealth Group Incorporated" },
  { sembol: "DIS", isim: "The Walt Disney Company" },
  { sembol: "HD", isim: "The Home Depot Inc." },
  { sembol: "BAC", isim: "Bank of America Corporation" },
  { sembol: "XOM", isim: "Exxon Mobil Corporation" },
  { sembol: "CVX", isim: "Chevron Corporation" },
  { sembol: "KO", isim: "The Coca-Cola Company" },
  { sembol: "PEP", isim: "PepsiCo Inc." },
  { sembol: "COST", isim: "Costco Wholesale Corporation" },
  { sembol: "PFE", isim: "Pfizer Inc." },
  { sembol: "MRK", isim: "Merck & Co. Inc." },
  { sembol: "TMO", isim: "Thermo Fisher Scientific Inc." },
  { sembol: "MCD", isim: "McDonald's Corporation" },
  { sembol: "CRM", isim: "Salesforce Inc." },
  { sembol: "CSCO", isim: "Cisco Systems Inc." },
  { sembol: "ABT", isim: "Abbott Laboratories" },
  { sembol: "ACN", isim: "Accenture plc" },
  { sembol: "NFLX", isim: "Netflix Inc." },
  { sembol: "ADBE", isim: "Adobe Inc." },
  { sembol: "INTC", isim: "Intel Corporation" },
  { sembol: "AMD", isim: "Advanced Micro Devices Inc." },
  { sembol: "CMCSA", isim: "Comcast Corporation" },
  { sembol: "NKE", isim: "NIKE Inc." },
  { sembol: "TXN", isim: "Texas Instruments Incorporated" },
  { sembol: "PM", isim: "Philip Morris International Inc." },
  { sembol: "LIN", isim: "Linde plc" },
  { sembol: "NEE", isim: "NextEra Energy Inc." },
  { sembol: "UNP", isim: "Union Pacific Corporation" },
  { sembol: "ORCL", isim: "Oracle Corporation" },
  { sembol: "WFC", isim: "Wells Fargo & Company" },
  { sembol: "QCOM", isim: "QUALCOMM Incorporated" },
  { sembol: "HON", isim: "Honeywell International Inc." },
  { sembol: "UPS", isim: "United Parcel Service Inc." },
  { sembol: "RTX", isim: "RTX Corporation" },
  { sembol: "BA", isim: "The Boeing Company" },
  { sembol: "IBM", isim: "International Business Machines Corporation" },
  { sembol: "LLY", isim: "Eli Lilly and Company" },
  { sembol: "SBUX", isim: "Starbucks Corporation" },
  { sembol: "GE", isim: "General Electric Company" },
  { sembol: "CAT", isim: "Caterpillar Inc." },
  { sembol: "GS", isim: "The Goldman Sachs Group Inc." },
  { sembol: "MS", isim: "Morgan Stanley" },
  { sembol: "BLK", isim: "BlackRock Inc." },
  { sembol: "MMM", isim: "3M Company" },
  { sembol: "C", isim: "Citigroup Inc." },
  { sembol: "AXP", isim: "American Express Company" },
  { sembol: "T", isim: "AT&T Inc." },
  { sembol: "VZ", isim: "Verizon Communications Inc." },
  { sembol: "F", isim: "Ford Motor Company" },
  { sembol: "GM", isim: "General Motors Company" },
  { sembol: "TGT", isim: "Target Corporation" },
  { sembol: "LOW", isim: "Lowe's Companies Inc." },
  { sembol: "CVS", isim: "CVS Health Corporation" },
  { sembol: "WBA", isim: "Walgreens Boots Alliance Inc." },
  { sembol: "BMY", isim: "Bristol-Myers Squibb Company" },
  { sembol: "GILD", isim: "Gilead Sciences Inc." },
  { sembol: "AMGN", isim: "Amgen Inc." },
  { sembol: "ISRG", isim: "Intuitive Surgical Inc." },
  { sembol: "MDT", isim: "Medtronic plc" },
  { sembol: "SYK", isim: "Stryker Corporation" },
  { sembol: "SPGI", isim: "S&P Global Inc." },
  { sembol: "INTU", isim: "Intuit Inc." },
  { sembol: "NOW", isim: "ServiceNow Inc." },
  { sembol: "PYPL", isim: "PayPal Holdings Inc." },
  { sembol: "SQ", isim: "Block Inc." },
  { sembol: "UBER", isim: "Uber Technologies Inc." },
  { sembol: "ABNB", isim: "Airbnb Inc." },
  { sembol: "SNOW", isim: "Snowflake Inc." },
  { sembol: "PLTR", isim: "Palantir Technologies Inc." },
  { sembol: "ROKU", isim: "Roku Inc." },
  { sembol: "ZM", isim: "Zoom Video Communications Inc." },
  { sembol: "DOCU", isim: "DocuSign Inc." },
  { sembol: "SPOT", isim: "Spotify Technology S.A." },
  { sembol: "SHOP", isim: "Shopify Inc." },
  { sembol: "CRWD", isim: "CrowdStrike Holdings Inc." },
  { sembol: "NET", isim: "Cloudflare Inc." },
  { sembol: "DDOG", isim: "Datadog Inc." },
  { sembol: "TEAM", isim: "Atlassian Corporation" },
  { sembol: "OKTA", isim: "Okta Inc." },
  { sembol: "ZS", isim: "Zscaler Inc." },
  { sembol: "PANW", isim: "Palo Alto Networks Inc." },
  { sembol: "FTNT", isim: "Fortinet Inc." },
  { sembol: "LMT", isim: "Lockheed Martin Corporation" },
  { sembol: "NOC", isim: "Northrop Grumman Corporation" },
  { sembol: "GD", isim: "General Dynamics Corporation" },
  { sembol: "DE", isim: "Deere & Company" },
  { sembol: "WM", isim: "Waste Management Inc." },
];

module.exports = {
  companySymbol,
  companySymbolAndName
};
